function A_sym = A_func(in1,u_sym)
%A_func
%    A_sym = A_func(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Apr-2025 22:36:39

x1 = in1(1,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = x4.^2;
t5 = x1.*(5.0./7.0);
t4 = t2.^2;
t6 = t5-1.519642857142857e-1;
A_sym = reshape([0.0,t3.*t4.*2.54530756753206e-3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t2.*4.182877287225114e-1-t2.*t3.*t6.*sin(x3).*7.126861189089769e-3,0.0,0.0,0.0,t4.*t6.*x4.*7.126861189089769e-3,1.0,-4.0e+1],[4,4]);
end
