function B_sym = B_func(in1,u_sym)
%B_func
%    B_sym = B_func(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2025 09:26:50

B_sym = [0.0;0.0;0.0;6.0e+1];
