function B_sym = B_func(in1,u_sym)
%B_func
%    B_sym = B_func(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Apr-2025 22:36:39

B_sym = [0.0;0.0;0.0;6.0e+1];
end
