function C_sym = C_func(in1,u_sym)
%C_func
%    C_sym = C_func(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2025 09:26:50

C_sym = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[2,4]);
