function C_sym = C_func(in1,u_sym)
%C_func
%    C_sym = C_func(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Apr-2025 22:36:39

C_sym = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[2,4]);
end
