function f_sym_continuous = f_fn(in1,u_sym)
%F_FN
%    F_SYM_CONTINUOUS = F_FN(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2025 09:26:50

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
f_sym_continuous = [x2;sin(x3).*4.182877287225114e-1+x4.^2.*cos(x3).^2.*(x1.*(5.0./7.0)-1.519642857142857e-1).*3.563430594544885e-3;x4;u_sym.*6.0e+1-x4.*4.0e+1];
