function h_sym_continuous = h_fn(in1,u_sym)
%H_FN
%    H_SYM_CONTINUOUS = H_FN(IN1,U_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2025 09:26:50

x1 = in1(1,:);
x3 = in1(3,:);
h_sym_continuous = [x1;x3];
