function Lf2h = Lf2h_fn(x1,x2,x3,x4)
%Lf2h_fn
%    Lf2h = Lf2h_fn(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Apr-2025 22:36:40

Lf2h = sin(x3).*4.182877287225114e-1+x4.^2.*cos(x3).^2.*(x1.*(5.0./7.0)-1.519642857142857e-1).*3.563430594544885e-3;
end
