function Lf3h_discard = Lf3h_fn(x1,x2,x3,x4,u)
%Lf3h_fn
%    Lf3h_discard = Lf3h_fn(X1,X2,X3,X4,U)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Apr-2025 21:48:46

t2 = cos(x3);
t3 = sin(x3);
t4 = x4.^2;
et1 = t3.*t4.*2.822563407365049e+38-t2.*u.*1.404859343190421e+24+t2.*x4.*1.12902536294602e+40-t3.*t4.*x1.*1.326704304284394e+39+t2.*u.*x1.*1.003464484422976e+25;
et2 = t2.*x1.*x4.*-5.306817217137578e+40+t2.*x2.*x4.*6.633521521421972e+38+1.090131772687052e+41;
Lf3h_discard = (t2.*x4.*(et1+et2))./2.606176796093e+41;
end
